import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const useUser = () => ({ user: null, loading: false });

export default function Home() {
  const { user, loading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!(user || loading)) {
      router.push("/login");
    }
    console.log(useUser);
  }, [user, loading]);

  return (
    <main className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">home</div>
    </main>
  );
}
